"""add stage 2 operations schema

Revision ID: e80f1b0bf63e
Revises:
Create Date: 2026-08-19 23:27:22.166993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e80f1b0bf63e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "carriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", "name", name="uq_carriers_agency_name"),
    )
    op.create_index(op.f("ix_carriers_agency_id"), "carriers", ["agency_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("AGENT", "MANAGER", name="userrole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('AGENT', 'MANAGER')", name="ck_users_role"),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_agency_active", "users", ["agency_id", "is_active"], unique=False)
    op.create_index("ix_users_agency_role", "users", ["agency_id", "role"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_token_hash"), "auth_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        "ix_auth_sessions_user_expiration", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "carrier_domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("carrier_id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(["carrier_id"], ["carriers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", "domain", name="uq_carrier_domains_agency_domain"),
    )
    op.create_index(
        "ix_carrier_domains_lookup",
        "carrier_domains",
        ["agency_id", "domain", "is_enabled"],
        unique=False,
    )
    op.create_table(
        "carrier_senders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("carrier_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(["carrier_id"], ["carriers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", "email", name="uq_carrier_senders_agency_email"),
    )
    op.create_index(
        "ix_carrier_senders_lookup",
        "carrier_senders",
        ["agency_id", "email", "is_enabled"],
        unique=False,
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("carrier_id", sa.Integer(), nullable=False),
        sa.Column("assigned_agent_id", sa.Integer(), nullable=True),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("policy_number", sa.String(length=100), nullable=True),
        sa.Column(
            "current_policy_status",
            sa.Enum(
                "ISSUED",
                "PENDING",
                "LAPSED",
                "DECLINED",
                "ACTIVE",
                "GRACE_PERIOD",
                "UNKNOWN",
                name="policystatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "NORMAL", "HIGH", "URGENT", name="priority", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("premium_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("current_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_policy_status IN ('ISSUED', 'PENDING', 'LAPSED', 'DECLINED', "
            "'ACTIVE', 'GRACE_PERIOD', 'UNKNOWN')",
            name="ck_cases_policy_status",
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')", name="ck_cases_priority"
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cases_agency_priority_status",
        "cases",
        ["agency_id", "priority", "current_policy_status"],
        unique=False,
    )
    op.create_index("ix_cases_assigned_agent", "cases", ["assigned_agent_id"], unique=False)
    op.create_index(
        "uq_cases_policy_identity",
        "cases",
        ["agency_id", "carrier_id", "policy_number"],
        unique=True,
        postgresql_where=sa.text("policy_number IS NOT NULL"),
    )
    op.create_table(
        "gmail_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gmail_address", sa.String(length=320), nullable=False),
        sa.Column("google_account_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CONNECTED",
                "NEEDS_REAUTH",
                "ERROR",
                "DISCONNECTED",
                name="gmailconnectionstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempted_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_summary", sa.String(length=500), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CONNECTED', 'NEEDS_REAUTH', 'ERROR', 'DISCONNECTED')",
            name="ck_gmail_connections_status",
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", "gmail_address", name="uq_gmail_agency_address"),
    )
    op.create_index(
        "ix_gmail_connections_owner_status",
        "gmail_connections",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "carrier_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("carrier_id", sa.Integer(), nullable=False),
        sa.Column("gmail_connection_id", sa.Integer(), nullable=True),
        sa.Column("gmail_message_id", sa.String(length=255), nullable=True),
        sa.Column("gmail_thread_id", sa.String(length=255), nullable=True),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "POLICY_ISSUED",
                "PENDING_REQUIREMENTS",
                "LAPSE_NOTICE",
                "COMMISSION_UPDATE",
                "OTHER",
                name="messageclassification",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "NORMAL", "HIGH", "URGENT", name="priority", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "RECEIVED",
                "PROCESSING",
                "PROCESSED",
                "NEEDS_REVIEW",
                "FAILED",
                "IGNORED",
                name="processingstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("cleaned_content", sa.Text(), nullable=False),
        sa.Column("original_deadline_text", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification IN ('POLICY_ISSUED', 'PENDING_REQUIREMENTS', 'LAPSE_NOTICE', "
            "'COMMISSION_UPDATE', 'OTHER')",
            name="ck_carrier_messages_classification",
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')", name="ck_carrier_messages_priority"
        ),
        sa.CheckConstraint(
            "processing_status IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'NEEDS_REVIEW', "
            "'FAILED', 'IGNORED')",
            name="ck_carrier_messages_processing_status",
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gmail_connection_id"],
            ["gmail_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gmail_connection_id", "gmail_message_id", name="uq_gmail_connection_message"
        ),
    )
    op.create_index(
        "ix_carrier_messages_agency_processing",
        "carrier_messages",
        ["agency_id", "processing_status"],
        unique=False,
    )
    op.create_index(
        "ix_carrier_messages_case_received",
        "carrier_messages",
        ["case_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carrier_message_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "PENDING",
                "EXTRACTED",
                "FAILED",
                "UNSUPPORTED",
                name="attachmentstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "processing_status IN ('PENDING', 'EXTRACTED', 'FAILED', 'UNSUPPORTED')",
            name="ck_attachments_processing_status",
        ),
        sa.ForeignKeyConstraint(
            ["carrier_message_id"], ["carrier_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachments_carrier_message_id"),
        "attachments",
        ["carrier_message_id"],
        unique=False,
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("carrier_message_id", sa.Integer(), nullable=False),
        sa.Column("assigned_reviewer_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_REVIEW",
                "RESOLVED",
                "DISMISSED",
                name="reviewstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED')",
            name="ck_review_items_status",
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_message_id"],
            ["carrier_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reviews_agency_status", "review_items", ["agency_id", "status"], unique=False
    )
    op.create_index(
        "ix_reviews_reviewer_status",
        "review_items",
        ["assigned_reviewer_id", "status"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("source_carrier_message_id", sa.Integer(), nullable=True),
        sa.Column("assigned_agent_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "NORMAL", "HIGH", "URGENT", name="priority", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "COMPLETED",
                "DISMISSED",
                name="taskstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')", name="ck_tasks_priority"
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'DISMISSED')", name="ck_tasks_status"
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_carrier_message_id"],
            ["carrier_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_agency_priority", "tasks", ["agency_id", "priority"], unique=False)
    op.create_index(
        "ix_tasks_assignee_status_due",
        "tasks",
        ["assigned_agent_id", "status", "due_at"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("carrier_message_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("INFO", "WARNING", "ERROR", name="auditseverity", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "severity IN ('INFO', 'WARNING', 'ERROR')", name="ck_audit_events_severity"
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_message_id"],
            ["carrier_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_agency_created", "audit_events", ["agency_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_agency_type", "audit_events", ["agency_id", "event_type"], unique=False
    )
    op.create_table(
        "case_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("carrier_message_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_message_id"],
            ["carrier_messages.id"],
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("case_evidence")
    op.drop_index("ix_audit_events_agency_type", table_name="audit_events")
    op.drop_index("ix_audit_events_agency_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_tasks_assignee_status_due", table_name="tasks")
    op.drop_index("ix_tasks_agency_priority", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_reviews_reviewer_status", table_name="review_items")
    op.drop_index("ix_reviews_agency_status", table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_attachments_carrier_message_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_carrier_messages_case_received", table_name="carrier_messages")
    op.drop_index("ix_carrier_messages_agency_processing", table_name="carrier_messages")
    op.drop_table("carrier_messages")
    op.drop_index("ix_gmail_connections_owner_status", table_name="gmail_connections")
    op.drop_table("gmail_connections")
    op.drop_index(
        "uq_cases_policy_identity",
        table_name="cases",
        postgresql_where=sa.text("policy_number IS NOT NULL"),
    )
    op.drop_index("ix_cases_assigned_agent", table_name="cases")
    op.drop_index("ix_cases_agency_priority_status", table_name="cases")
    op.drop_table("cases")
    op.drop_index("ix_carrier_senders_lookup", table_name="carrier_senders")
    op.drop_table("carrier_senders")
    op.drop_index("ix_carrier_domains_lookup", table_name="carrier_domains")
    op.drop_table("carrier_domains")
    op.drop_index("ix_auth_sessions_user_expiration", table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_token_hash"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_users_agency_role", table_name="users")
    op.drop_index("ix_users_agency_active", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_carriers_agency_id"), table_name="carriers")
    op.drop_table("carriers")
    op.drop_table("agencies")
    # ### end Alembic commands ###
